swagger: "2.0"
info:
  version: "0.0.1"
  title: Startegy Service
# during dev, should point to your local machine
host: localhost:10020
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

securityDefinitions:
#  oauth2_google: 
#    type: oauth2
#    scopes:
#      read:strategies: 'Read access to stewards'
#    flow: accessCode
#    authorizationUrl: http://127.0.0.1:10020/auth/google
#    x-authroization-operation-id: authenticateWithGoogle
#    tokenUrl: http://127.0.0.1:10020/auth/google/callback
#    x-token-operation-id: authenticationCallBackWithGoogle
  jwt:
    type: apiKey
    in: header
    name: JWT-TOKEN
  api_key:
    type: apiKey
    in: header
    name: api-key
paths:
  /strategies:
    x-swagger-router-controller: strategy.controller
    get:
      security:
      - jwt: []
      - api_key: []
      description: Returns a list of available strategies
      produces:
        - application/json
      operationId: getStrategies
      parameters: 
        - name: _id
          in: query
          description: The id of a specific strategy
          required: false
          type: string
      responses:
        "200":
          description: A list of strategies
          schema: 
            type: array
            items:
              $ref: "#/definitions/Strategy"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      security:
        - jwt: []
      description: adds a new strategy
      produces:
        - application/json
      operationId: postStrategies
      parameters:
        - name: strategy
          description: the complete strategy object
          in: body
          required: true
          schema:
            $ref: "#/definitions/Strategy"
      responses:
        200:
          description: OK - created successfully
          schema: 
            $ref: "#/definitions/Strategy"

  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      security:
        - jwt: []
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Strategy:
    type: object
    required:
      - id
      - name
      - description
      - createdTime
      - isActive
      - granularity
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      createdTime:
        type: string
        format: date-time
      isActive:
        type: boolean
      granularity:
        type: string
        enum:
          - M5
          - M15
          - M30
          - H1
          - H4
          - D1
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    properties:
      message:
        type: string
    required:
      - message